//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtGoxTrader.Trader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MtGoxTrader.Trader.Strings.en.us", typeof(Strings_en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutSubMenu {
            get {
                return ResourceManager.GetString("AboutSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is above .
        /// </summary>
        internal static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account summary.
        /// </summary>
        internal static string AccountTab {
            get {
                return ResourceManager.GetString("AccountTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is already running.
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        internal static string AlwaysInFront {
            get {
                return ResourceManager.GetString("AlwaysInFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic trade.
        /// </summary>
        internal static string AutomaticTrade {
            get {
                return ResourceManager.GetString("AutomaticTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto refresh.
        /// </summary>
        internal static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If buy amount in 10 order is greater than.
        /// </summary>
        internal static string AutoTradeBuyAmountIn10Higher {
            get {
                return ResourceManager.GetString("AutoTradeBuyAmountIn10Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If daily price drop is greater than .
        /// </summary>
        internal static string AutoTradeDailyDropHigher {
            get {
                return ResourceManager.GetString("AutoTradeDailyDropHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If daily price drop is less than.
        /// </summary>
        internal static string AutoTradeDailyDropLower {
            get {
                return ResourceManager.GetString("AutoTradeDailyDropLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If daily price increase is greater than .
        /// </summary>
        internal static string AutoTradeDailyIncreaseHigher {
            get {
                return ResourceManager.GetString("AutoTradeDailyIncreaseHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If daily price increase is less than.
        /// </summary>
        internal static string AutoTradeDailyIncreaseLower {
            get {
                return ResourceManager.GetString("AutoTradeDailyIncreaseLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string AutoTradeDelete {
            get {
                return ResourceManager.GetString("AutoTradeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 5 minutes single trade&apos;s amount is greater than.
        /// </summary>
        internal static string AutoTradeFiveMinAmountPerTradeHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinAmountPerTradeHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 5 minutes deal amount is greater than.
        /// </summary>
        internal static string AutoTradeFiveMinDealAmountHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinDealAmountHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 5 minutes price drop is greater than.
        /// </summary>
        internal static string AutoTradeFiveMinDropHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinDropHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 5 minutes price increase is greater than.
        /// </summary>
        internal static string AutoTradeFiveMinIncreaseHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinIncreaseHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the automatic trade strategy is not ready in this version.
        /// </summary>
        internal static string AutoTradeNotReady {
            get {
                return ResourceManager.GetString("AutoTradeNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 1 minute single trade&apos;s amount is greater than.
        /// </summary>
        internal static string AutoTradeOneMinAmountPerTradeHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinAmountPerTradeHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 1 minute deal amount is greater than.
        /// </summary>
        internal static string AutoTradeOneMinDealAmountHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinDealAmountHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 1 minute price drop is greater than.
        /// </summary>
        internal static string AutoTradeOneMinDropHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinDropHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If 1 minute price increase is greater than.
        /// </summary>
        internal static string AutoTradeOneMinIncreaseHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinIncreaseHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If price is higher than .
        /// </summary>
        internal static string AutoTradePriceHigher {
            get {
                return ResourceManager.GetString("AutoTradePriceHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If price is lower than .
        /// </summary>
        internal static string AutoTradePriceLower {
            get {
                return ResourceManager.GetString("AutoTradePriceLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string AutoTradeRuleCondition {
            get {
                return ResourceManager.GetString("AutoTradeRuleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule already added.
        /// </summary>
        internal static string AutoTradeRuleExisted {
            get {
                return ResourceManager.GetString("AutoTradeRuleExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If sell amount in 10 order is greater than.
        /// </summary>
        internal static string AutoTradeSellAmountIn10Higher {
            get {
                return ResourceManager.GetString("AutoTradeSellAmountIn10Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If trade swing is greater than.
        /// </summary>
        internal static string AutoTradeSwing {
            get {
                return ResourceManager.GetString("AutoTradeSwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoins .
        /// </summary>
        internal static string AvailBtcAmount {
            get {
                return ResourceManager.GetString("AvailBtcAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available amount.
        /// </summary>
        internal static string AvailBuyCount {
            get {
                return ResourceManager.GetString("AvailBuyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds .
        /// </summary>
        internal static string AvailFundAmount {
            get {
                return ResourceManager.GetString("AvailFundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available amount.
        /// </summary>
        internal static string AvailSellCount {
            get {
                return ResourceManager.GetString("AvailSellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average price.
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is below .
        /// </summary>
        internal static string Below {
            get {
                return ResourceManager.GetString("Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btc balance.
        /// </summary>
        internal static string BtcAmount {
            get {
                return ResourceManager.GetString("BtcAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade history.
        /// </summary>
        internal static string ButtonTradeTime {
            get {
                return ResourceManager.GetString("ButtonTradeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string BuyAmount {
            get {
                return ResourceManager.GetString("BuyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string BuyCustomize {
            get {
                return ResourceManager.GetString("BuyCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string BuyPrice {
            get {
                return ResourceManager.GetString("BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string BuyStop {
            get {
                return ResourceManager.GetString("BuyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string BuyType {
            get {
                return ResourceManager.GetString("BuyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string ConfigSubMenu {
            get {
                return ResourceManager.GetString("ConfigSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MtGox API Configuration.
        /// </summary>
        internal static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input MtGox API key &amp; secret.
        /// </summary>
        internal static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ConfigurationFinished {
            get {
                return ResourceManager.GetString("ConfigurationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current buy price.
        /// </summary>
        internal static string CurrentBuyPrice {
            get {
                return ResourceManager.GetString("CurrentBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current price.
        /// </summary>
        internal static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sell price.
        /// </summary>
        internal static string CurrentSellPrice {
            get {
                return ResourceManager.GetString("CurrentSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed.
        /// </summary>
        internal static string Executed {
            get {
                return ResourceManager.GetString("Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is expired.
        /// </summary>
        internal static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund balance.
        /// </summary>
        internal static string FundAmount {
            get {
                return ResourceManager.GetString("FundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest price.
        /// </summary>
        internal static string HighestPrice {
            get {
                return ResourceManager.GetString("HighestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryTab {
            get {
                return ResourceManager.GetString("HistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade information.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input error.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any problems, please contact: .
        /// </summary>
        internal static string LabelHelp {
            get {
                return ResourceManager.GetString("LabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh period.
        /// </summary>
        internal static string LabelRefreshTime {
            get {
                return ResourceManager.GetString("LabelRefreshTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show amount greater than.
        /// </summary>
        internal static string LabelTradeMinAmount {
            get {
                return ResourceManager.GetString("LabelTradeMinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language.
        /// </summary>
        internal static string LanguageSubMenu {
            get {
                return ResourceManager.GetString("LanguageSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should request a serial NO to register this software.
        /// </summary>
        internal static string lblRequiredReg {
            get {
                return ResourceManager.GetString("lblRequiredReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string LinkNext {
            get {
                return ResourceManager.GetString("LinkNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string LinkPrev {
            get {
                return ResourceManager.GetString("LinkPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings.
        /// </summary>
        internal static string LoadSettingsSubMenu {
            get {
                return ResourceManager.GetString("LoadSettingsSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        internal static string MachineCode {
            get {
                return ResourceManager.GetString("MachineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string MarketSummaryHeadAmount {
            get {
                return ResourceManager.GetString("MarketSummaryHeadAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BTC.
        /// </summary>
        internal static string MarketSummaryHeadBtcAmount {
            get {
                return ResourceManager.GetString("MarketSummaryHeadBtcAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Funds.
        /// </summary>
        internal static string MarketSummaryHeadFundAmount {
            get {
                return ResourceManager.GetString("MarketSummaryHeadFundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string MarketSummaryHeadPrice {
            get {
                return ResourceManager.GetString("MarketSummaryHeadPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market value.
        /// </summary>
        internal static string MarketValue {
            get {
                return ResourceManager.GetString("MarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MenuItemClose {
            get {
                return ResourceManager.GetString("MenuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string MenuItemShow {
            get {
                return ResourceManager.GetString("MenuItemShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Trader.
        /// </summary>
        internal static string Minimized {
            get {
                return ResourceManager.GetString("Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neweast price .
        /// </summary>
        internal static string NeweastPrice {
            get {
                return ResourceManager.GetString("NeweastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string OrderAction {
            get {
                return ResourceManager.GetString("OrderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been placed.
        /// </summary>
        internal static string OrderSucceed {
            get {
                return ResourceManager.GetString("OrderSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed.
        /// </summary>
        internal static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string OrderTotal {
            get {
                return ResourceManager.GetString("OrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        internal static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit ratio.
        /// </summary>
        internal static string ProfitRate {
            get {
                return ResourceManager.GetString("ProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitSubMenu {
            get {
                return ResourceManager.GetString("QuitSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register failed.
        /// </summary>
        internal static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register succeeded.
        /// </summary>
        internal static string RegisterSucceed {
            get {
                return ResourceManager.GetString("RegisterSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining days: .
        /// </summary>
        internal static string RemainingDays {
            get {
                return ResourceManager.GetString("RemainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Serial NO.
        /// </summary>
        internal static string RequestSerial {
            get {
                return ResourceManager.GetString("RequestSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string SaveSettingsSubMenu {
            get {
                return ResourceManager.GetString("SaveSettingsSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string SellAmount {
            get {
                return ResourceManager.GetString("SellAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string SellCustomize {
            get {
                return ResourceManager.GetString("SellCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string SellMarket {
            get {
                return ResourceManager.GetString("SellMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string SellStopLimit {
            get {
                return ResourceManager.GetString("SellStopLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SellType {
            get {
                return ResourceManager.GetString("SellType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this software, please send bitcoin to .
        /// </summary>
        internal static string SendBtcToMe {
            get {
                return ResourceManager.GetString("SendBtcToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial NO.
        /// </summary>
        internal static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong with this software.
        /// </summary>
        internal static string SetupWrong {
            get {
                return ResourceManager.GetString("SetupWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show depth .
        /// </summary>
        internal static string ShowDepth {
            get {
                return ResourceManager.GetString("ShowDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MtGox Trader.
        /// </summary>
        internal static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade strategy.
        /// </summary>
        internal static string TabTradeStrategy {
            get {
                return ResourceManager.GetString("TabTradeStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        internal static string TickerTab {
            get {
                return ResourceManager.GetString("TickerTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TradeAmount {
            get {
                return ResourceManager.GetString("TradeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TradeHeadAmount {
            get {
                return ResourceManager.GetString("TradeHeadAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string TradeHeadPrice {
            get {
                return ResourceManager.GetString("TradeHeadPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade history.
        /// </summary>
        internal static string TradeHistoryTab {
            get {
                return ResourceManager.GetString("TradeHistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string TradePrice {
            get {
                return ResourceManager.GetString("TradePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string TradeTab {
            get {
                return ResourceManager.GetString("TradeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TradeTime {
            get {
                return ResourceManager.GetString("TradeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TradeType {
            get {
                return ResourceManager.GetString("TradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If buy price is above.
        /// </summary>
        internal static string WarnBuyPrice {
            get {
                return ResourceManager.GetString("WarnBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning sound.
        /// </summary>
        internal static string WarningSound {
            get {
                return ResourceManager.GetString("WarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If sell price is below .
        /// </summary>
        internal static string WarnSellPrice {
            get {
                return ResourceManager.GetString("WarnSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        internal static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
    }
}
