//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtGoxTrader.Trader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_zh_cn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MtGoxTrader.Trader.Strings.zh.cn", typeof(Strings_zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string AboutSubMenu {
            get {
                return ResourceManager.GetString("AboutSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高于.
        /// </summary>
        internal static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户概览.
        /// </summary>
        internal static string AccountTab {
            get {
                return ResourceManager.GetString("AccountTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已有相同的实例在运行.
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序置顶.
        /// </summary>
        internal static string AlwaysInFront {
            get {
                return ResourceManager.GetString("AlwaysInFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动交易.
        /// </summary>
        internal static string AutomaticTrade {
            get {
                return ResourceManager.GetString("AutomaticTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动刷新.
        /// </summary>
        internal static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当10档买单挂盘数量大于.
        /// </summary>
        internal static string AutoTradeBuyAmountIn10Higher {
            get {
                return ResourceManager.GetString("AutoTradeBuyAmountIn10Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当今日跌幅大于.
        /// </summary>
        internal static string AutoTradeDailyDropHigher {
            get {
                return ResourceManager.GetString("AutoTradeDailyDropHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当今日跌幅小于.
        /// </summary>
        internal static string AutoTradeDailyDropLower {
            get {
                return ResourceManager.GetString("AutoTradeDailyDropLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当今日涨幅大于.
        /// </summary>
        internal static string AutoTradeDailyIncreaseHigher {
            get {
                return ResourceManager.GetString("AutoTradeDailyIncreaseHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当今日涨幅低于.
        /// </summary>
        internal static string AutoTradeDailyIncreaseLower {
            get {
                return ResourceManager.GetString("AutoTradeDailyIncreaseLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string AutoTradeDelete {
            get {
                return ResourceManager.GetString("AutoTradeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当5分钟单笔成交量大于.
        /// </summary>
        internal static string AutoTradeFiveMinAmountPerTradeHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinAmountPerTradeHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当5分钟成交量大于.
        /// </summary>
        internal static string AutoTradeFiveMinDealAmountHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinDealAmountHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当5分钟跌幅大于.
        /// </summary>
        internal static string AutoTradeFiveMinDropHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinDropHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当5分钟涨幅大于.
        /// </summary>
        internal static string AutoTradeFiveMinIncreaseHigher {
            get {
                return ResourceManager.GetString("AutoTradeFiveMinIncreaseHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对不起，此版本无自动交易策略模块.
        /// </summary>
        internal static string AutoTradeNotReady {
            get {
                return ResourceManager.GetString("AutoTradeNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当1分钟单笔成交量大于.
        /// </summary>
        internal static string AutoTradeOneMinAmountPerTradeHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinAmountPerTradeHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当1分钟成交量大于.
        /// </summary>
        internal static string AutoTradeOneMinDealAmountHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinDealAmountHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当1分钟跌幅大于.
        /// </summary>
        internal static string AutoTradeOneMinDropHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinDropHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当1分钟涨幅大于.
        /// </summary>
        internal static string AutoTradeOneMinIncreaseHigher {
            get {
                return ResourceManager.GetString("AutoTradeOneMinIncreaseHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当价格高于.
        /// </summary>
        internal static string AutoTradePriceHigher {
            get {
                return ResourceManager.GetString("AutoTradePriceHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当价格低于.
        /// </summary>
        internal static string AutoTradePriceLower {
            get {
                return ResourceManager.GetString("AutoTradePriceLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易条件.
        /// </summary>
        internal static string AutoTradeRuleCondition {
            get {
                return ResourceManager.GetString("AutoTradeRuleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该交易条件已存在.
        /// </summary>
        internal static string AutoTradeRuleExisted {
            get {
                return ResourceManager.GetString("AutoTradeRuleExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当10档卖单挂盘数量大于.
        /// </summary>
        internal static string AutoTradeSellAmountIn10Higher {
            get {
                return ResourceManager.GetString("AutoTradeSellAmountIn10Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当振幅大于.
        /// </summary>
        internal static string AutoTradeSwing {
            get {
                return ResourceManager.GetString("AutoTradeSwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余BTC.
        /// </summary>
        internal static string AvailBtcAmount {
            get {
                return ResourceManager.GetString("AvailBtcAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可买数量.
        /// </summary>
        internal static string AvailBuyCount {
            get {
                return ResourceManager.GetString("AvailBuyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余资金.
        /// </summary>
        internal static string AvailFundAmount {
            get {
                return ResourceManager.GetString("AvailFundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可卖数量.
        /// </summary>
        internal static string AvailSellCount {
            get {
                return ResourceManager.GetString("AvailSellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均价格.
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资金余额.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低于.
        /// </summary>
        internal static string Below {
            get {
                return ResourceManager.GetString("Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btc余额.
        /// </summary>
        internal static string BtcAmount {
            get {
                return ResourceManager.GetString("BtcAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看该时交易.
        /// </summary>
        internal static string ButtonTradeTime {
            get {
                return ResourceManager.GetString("ButtonTradeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 买入.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 买入数量.
        /// </summary>
        internal static string BuyAmount {
            get {
                return ResourceManager.GetString("BuyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string BuyCustomize {
            get {
                return ResourceManager.GetString("BuyCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 买入价格.
        /// </summary>
        internal static string BuyPrice {
            get {
                return ResourceManager.GetString("BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 市价买入.
        /// </summary>
        internal static string BuyStop {
            get {
                return ResourceManager.GetString("BuyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托方式.
        /// </summary>
        internal static string BuyType {
            get {
                return ResourceManager.GetString("BuyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string ConfigSubMenu {
            get {
                return ResourceManager.GetString("ConfigSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MtGox API 设置.
        /// </summary>
        internal static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入MtGox API Key和MtGox API Secret.
        /// </summary>
        internal static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置完成.
        /// </summary>
        internal static string ConfigurationFinished {
            get {
                return ResourceManager.GetString("ConfigurationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系邮箱.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成本.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 币种.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前买家价格.
        /// </summary>
        internal static string CurrentBuyPrice {
            get {
                return ResourceManager.GetString("CurrentBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前价格.
        /// </summary>
        internal static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前卖家价格.
        /// </summary>
        internal static string CurrentSellPrice {
            get {
                return ResourceManager.GetString("CurrentSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易日期.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存入.
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已执行.
        /// </summary>
        internal static string Executed {
            get {
                return ResourceManager.GetString("Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件已过期.
        /// </summary>
        internal static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资金余额.
        /// </summary>
        internal static string FundAmount {
            get {
                return ResourceManager.GetString("FundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高价.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高价格.
        /// </summary>
        internal static string HighestPrice {
            get {
                return ResourceManager.GetString("HighestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易记录.
        /// </summary>
        internal static string HistoryTab {
            get {
                return ResourceManager.GetString("HistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易信息.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入错误.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此版本为内测软件，如果遇到任何问题，请联系：.
        /// </summary>
        internal static string LabelHelp {
            get {
                return ResourceManager.GetString("LabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新时间.
        /// </summary>
        internal static string LabelRefreshTime {
            get {
                return ResourceManager.GetString("LabelRefreshTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示数量大于.
        /// </summary>
        internal static string LabelTradeMinAmount {
            get {
                return ResourceManager.GetString("LabelTradeMinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言设置.
        /// </summary>
        internal static string LanguageSubMenu {
            get {
                return ResourceManager.GetString("LanguageSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本软件是内测软件，您需要获得邀请注册序列号才能注册成为内测用户.
        /// </summary>
        internal static string lblRequiredReg {
            get {
                return ResourceManager.GetString("lblRequiredReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        internal static string LinkNext {
            get {
                return ResourceManager.GetString("LinkNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        internal static string LinkPrev {
            get {
                return ResourceManager.GetString("LinkPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入设置.
        /// </summary>
        internal static string LoadSettingsSubMenu {
            get {
                return ResourceManager.GetString("LoadSettingsSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低价.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string MachineCode {
            get {
                return ResourceManager.GetString("MachineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量（单数）.
        /// </summary>
        internal static string MarketSummaryHeadAmount {
            get {
                return ResourceManager.GetString("MarketSummaryHeadAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 累计BTC数量.
        /// </summary>
        internal static string MarketSummaryHeadBtcAmount {
            get {
                return ResourceManager.GetString("MarketSummaryHeadBtcAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 累计金额.
        /// </summary>
        internal static string MarketSummaryHeadFundAmount {
            get {
                return ResourceManager.GetString("MarketSummaryHeadFundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格.
        /// </summary>
        internal static string MarketSummaryHeadPrice {
            get {
                return ResourceManager.GetString("MarketSummaryHeadPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 市值.
        /// </summary>
        internal static string MarketValue {
            get {
                return ResourceManager.GetString("MarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string MenuItemClose {
            get {
                return ResourceManager.GetString("MenuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示.
        /// </summary>
        internal static string MenuItemShow {
            get {
                return ResourceManager.GetString("MenuItemShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Trader.
        /// </summary>
        internal static string Minimized {
            get {
                return ResourceManager.GetString("Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新价格.
        /// </summary>
        internal static string NeweastPrice {
            get {
                return ResourceManager.GetString("NeweastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        internal static string OrderAction {
            get {
                return ResourceManager.GetString("OrderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托数量.
        /// </summary>
        internal static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托价格.
        /// </summary>
        internal static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托成功.
        /// </summary>
        internal static string OrderSucceed {
            get {
                return ResourceManager.GetString("OrderSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下单时间.
        /// </summary>
        internal static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合计金额.
        /// </summary>
        internal static string OrderTotal {
            get {
                return ResourceManager.GetString("OrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托类型.
        /// </summary>
        internal static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未执行.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 累计盈亏.
        /// </summary>
        internal static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 盈亏比例.
        /// </summary>
        internal static string ProfitRate {
            get {
                return ResourceManager.GetString("ProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string QuitSubMenu {
            get {
                return ResourceManager.GetString("QuitSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册失败，请输入正确的序列号或者联系我们.
        /// </summary>
        internal static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功，感谢您的支持!.
        /// </summary>
        internal static string RegisterSucceed {
            get {
                return ResourceManager.GetString("RegisterSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎您使用MtGoxTrade软件.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此版本为内测版本，仅供试用和收集建议之用途 剩余天数： .
        /// </summary>
        internal static string RemainingDays {
            get {
                return ResourceManager.GetString("RemainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取序列号.
        /// </summary>
        internal static string RequestSerial {
            get {
                return ResourceManager.GetString("RequestSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存设置.
        /// </summary>
        internal static string SaveSettingsSubMenu {
            get {
                return ResourceManager.GetString("SaveSettingsSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卖出.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卖出数量.
        /// </summary>
        internal static string SellAmount {
            get {
                return ResourceManager.GetString("SellAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string SellCustomize {
            get {
                return ResourceManager.GetString("SellCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 市价委托.
        /// </summary>
        internal static string SellMarket {
            get {
                return ResourceManager.GetString("SellMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卖出价格.
        /// </summary>
        internal static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限价止损.
        /// </summary>
        internal static string SellStopLimit {
            get {
                return ResourceManager.GetString("SellStopLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动止损.
        /// </summary>
        internal static string SellTrailingStop {
            get {
                return ResourceManager.GetString("SellTrailingStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托方式.
        /// </summary>
        internal static string SellType {
            get {
                return ResourceManager.GetString("SellType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果您支持本软件，请发送bitcoin到 .
        /// </summary>
        internal static string SendBtcToMe {
            get {
                return ResourceManager.GetString("SendBtcToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序列号.
        /// </summary>
        internal static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置已保存.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序安装出错.
        /// </summary>
        internal static string SetupWrong {
            get {
                return ResourceManager.GetString("SetupWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示交易深度 .
        /// </summary>
        internal static string ShowDepth {
            get {
                return ResourceManager.GetString("ShowDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MtGox Trader.
        /// </summary>
        internal static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 声音.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易策略.
        /// </summary>
        internal static string TabTradeStrategy {
            get {
                return ResourceManager.GetString("TabTradeStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 买入卖出.
        /// </summary>
        internal static string TickerTab {
            get {
                return ResourceManager.GetString("TickerTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易数量.
        /// </summary>
        internal static string TradeAmount {
            get {
                return ResourceManager.GetString("TradeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        internal static string TradeHeadAmount {
            get {
                return ResourceManager.GetString("TradeHeadAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格.
        /// </summary>
        internal static string TradeHeadPrice {
            get {
                return ResourceManager.GetString("TradeHeadPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 盘口信息.
        /// </summary>
        internal static string TradeHistoryTab {
            get {
                return ResourceManager.GetString("TradeHistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易价格.
        /// </summary>
        internal static string TradePrice {
            get {
                return ResourceManager.GetString("TradePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托查询.
        /// </summary>
        internal static string TradeTab {
            get {
                return ResourceManager.GetString("TradeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易时间.
        /// </summary>
        internal static string TradeTime {
            get {
                return ResourceManager.GetString("TradeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易类型.
        /// </summary>
        internal static string TradeType {
            get {
                return ResourceManager.GetString("TradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易类型.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成交金额.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成交量.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当买入价格高于.
        /// </summary>
        internal static string WarnBuyPrice {
            get {
                return ResourceManager.GetString("WarnBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报警声音.
        /// </summary>
        internal static string WarningSound {
            get {
                return ResourceManager.GetString("WarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当卖出价格低于.
        /// </summary>
        internal static string WarnSellPrice {
            get {
                return ResourceManager.GetString("WarnSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取出.
        /// </summary>
        internal static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
    }
}
